#!/bin/sh

# $Id: test-echoping-icp 377 2007-03-12 20:48:05Z bortz $

echo ""
echo "Since this tests tries remote servers, a failure is not always "
echo " echoping's fault: it may be a network problem. Also, it depends on"
echo " a local ICP cache named 'cache'."

./echoping -i http://www.pasteur.fr/ cache

./echoping -i http://www.freenix.org/ cache


